OneDrive/Desktop/Unique/Cafe_Project_MS.NET-master/Cafe_System/RolesAuth/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using RolesAuth.Data;

namespace RolesAuth.Controllers
{
    //[Authorize (Roles ="Admin")]
    public class AppRolesController : Controller
    {
        
        private readonly RoleManager<IdentityRole> roleManager;

        public AppRolesController( RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
            
        }

        //lists all the roles created by users
        public IActionResult Index()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {

            //avoid duplicate role
            var isThere = roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult();

            if (!isThere)
            {
                roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || roleManager.Roles == null)
            {
                return NotFound();
            }

            var roleEntity = await roleManager.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (roleEntity == null)
            {
                return NotFound();
            }

            return View(roleEntity);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (roleManager.Roles == null)
            {
                return Problem("Entity set 'AppDbContext.Roles' is null.");
            }

            var roleEntity = await roleManager.FindByIdAsync(id);
            if (roleEntity != null)
            {
                var result = await roleManager.DeleteAsync(roleEntity);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    // Handle the error, e.g., return a view with error messages
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return NotFound();
            }
        }
    }
    
}

OneDrive/Desktop/Unique/Cafe_Project_MS.NET-master/Cafe_System/RolesAuth/Controllers/CafeEntitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RolesAuth.Data;
using RolesAuth.Models;

namespace RolesAuth.Controllers
{
    public class CafeEntitiesController : Controller
    {
        private readonly AppDbContext _context;

        public CafeEntitiesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: CafeEntities
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Cafes.Include(c => c.User);
            return View(await appDbContext.ToListAsync());
        }

        // GET: CafeEntities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cafes == null)
            {
                return NotFound();
            }

            var cafeEntity = await _context.Cafes
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CafeId == id);
            if (cafeEntity == null)
            {
                return NotFound();
            }

            return View(cafeEntity);
        }

        // GET: CafeEntities/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id");
            return View();
        }

        // POST: CafeEntities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CafeId,Name,Email,Address,UserId")] CafeEntity cafeEntity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cafeEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", cafeEntity.UserId);
            return View(cafeEntity);
        }

        // GET: CafeEntities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cafes == null)
            {
                return NotFound();
            }

            var cafeEntity = await _context.Cafes.FindAsync(id);
            if (cafeEntity == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", cafeEntity.UserId);
            return View(cafeEntity);
        }

        // POST: CafeEntities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CafeId,Name,Email,Address,UserId")] CafeEntity cafeEntity)
        {
            if (id != cafeEntity.CafeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cafeEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CafeEntityExists(cafeEntity.CafeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", cafeEntity.UserId);
            return View(cafeEntity);
        }

        // GET: CafeEntities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cafes == null)
            {
                return NotFound();
            }

            var cafeEntity = await _context.Cafes
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CafeId == id);
            if (cafeEntity == null)
            {
                return NotFound();
            }

            return View(cafeEntity);
        }

        // POST: CafeEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cafes == null)
            {
                return Problem("Entity set 'AppDbContext.Cafes'  is null.");
            }
            var cafeEntity = await _context.Cafes.FindAsync(id);
            if (cafeEntity != null)
            {
                _context.Cafes.Remove(cafeEntity);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CafeEntityExists(int id)
        {
          return (_context.Cafes?.Any(e => e.CafeId == id)).GetValueOrDefault();
        }
    }
}

OneDrive/Desktop/Unique/Cafe_Project_MS.NET-master/Cafe_System/RolesAuth/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RolesAuth.Data;
using RolesAuth.Models;

namespace RolesAuth.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly AppDbContext _context;

        public CartItemsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: CartItems
        public async Task<IActionResult> Index()
        {
              return _context.CartItems != null ? 
                          View(await _context.CartItems.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.CartItems'  is null.");
        }

        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems
                .FirstOrDefaultAsync(m => m.CartFood_id == id);
            if (cartItems == null)
            {
                return NotFound();
            }

            return View(cartItems);
        }

        // GET: CartItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CartFood_id,CartFood_name,Cafe_name,Category,Price,Quantity")] CartItems cartItems)
        {
            /*if (ModelState.IsValid)
            {*/
                _context.Add(cartItems);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            /*}*/
            return View(cartItems);
        }

        // GET: CartItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems.FindAsync(id);
            if (cartItems == null)
            {
                return NotFound();
            }
            return View(cartItems);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CartFood_id,CartFood_name,Cafe_name,Category,Price,Quantity")] CartItems cartItems)
        {
            if (id != cartItems.CartFood_id)
            {
                return NotFound();
            }

            /*if (ModelState.IsValid)
            {*/
                try
                {
                    _context.Update(cartItems);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemsExists(cartItems.CartFood_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            /*}*/
            return View(cartItems);
        }

        // GET: CartItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems
                .FirstOrDefaultAsync(m => m.CartFood_id == id);
            if (cartItems == null)
            {
                return NotFound();
            }

            return View(cartItems);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CartItems == null)
            {
                return Problem("Entity set 'AppDbContext.CartItems'  is null.");
            }
            var cartItems = await _context.CartItems.FindAsync(id);
            if (cartItems != null)
            {
                _context.CartItems.Remove(cartItems);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartItemsExists(int id)
        {
          return (_context.CartItems?.Any(e => e.CartFood_id == id)).GetValueOrDefault();
        }
    }
}

OneDrive/Desktop/Unique/Cafe_Project_MS.NET-master/Cafe_System/RolesAuth/Views/Shared/Components/ImageUploader/ImageUploaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace RolesAuth.Views.Shared.Components.ImageUploader
{
    public class ImageUploaderViewComponent : ViewComponent
    {
        public ImageUploaderViewComponent()
        {

        }
        public IViewComponentResult Invoke(string FieldName)
        {
            return View("Default", FieldName);
        }
    }
}

OneDrive/Desktop/Unique/Cafe_Project_MS.NET-master/Cafe_System/RolesAuth/Views/Shared/Search.cshtml
<head>
    <link rel="stylesheet" href="~/css/Search.css" />
</head>


<div class="containerr">

    <div class="row height d-flex justify-content-center align-items-center">

        <div class="col-md-6">

            <div class="form">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 101 101" id="search" height="30" width="30" class="fa-search"><path d="M63.3 59.9c3.8-4.6 6.2-10.5 6.2-17 0-14.6-11.9-26.5-26.5-26.5S16.5 28.3 16.5 42.9 28.4 69.4 43 69.4c6.4 0 12.4-2.3 17-6.2l20.6 20.6c.5.5 1.1.7 1.7.7.6 0 1.2-.2 1.7-.7.9-.9.9-2.5 0-3.4L63.3 59.9zm-20.4 4.7c-12 0-21.7-9.7-21.7-21.7s9.7-21.7 21.7-21.7 21.7 9.7 21.7 21.7-9.7 21.7-21.7 21.7z"></path></svg>
                <input type="text" class="form-control form-input" placeholder="Search anything...">
                <span class="left-pan"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" id="microphone" height="30" width="30"><path d="M26,15a1,1,0,0,0-1,1A9,9,0,0,1,7,16a1,1,0,0,0-2,0A11,11,0,0,0,15,27V30a1,1,0,0,0,2,0V27A11,11,0,0,0,27,16,1,1,0,0,0,26,15Z"></path><path d="M16,21a6,6,0,0,0,6-6V7A6,6,0,0,0,10,7v8A6,6,0,0,0,16,21Z"></path></svg></span>
            </div>

        </div>

    </div>

</div>

OneDrive/Desktop/Unique/Cafe_Project_MS.NET-master/Cafe_System/RolesAuth/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RolesAuth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RolesAuth.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary  border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src='https://cdn-icons-png.flaticon.com/512/9620/9620771.png' alt="Logo" class="navbar-logo" />
                    CafeTo
                </a> <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="AppRoles" asp-action="Index">Roles</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link " id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="CafeEntities" asp-action="Index">Cafes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="CategoriesEntities" asp-action="Index">Categories</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <Partial name="Footer"/>
    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RolesAuth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OneDrive/Desktop/Unique/Cafe_Project_MS.NET-master/Cafe_System/RolesAuth/Views/Shared/_Customer.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RolesAuth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RolesAuth.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary  border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src='https://cdn-icons-png.flaticon.com/512/9620/9620771.png' alt="Logo" class="navbar-logo" />
                    CafeTo
                </a> 
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @* <li class="nav-item"
                            <a class="nav-link " asp-area="" asp-controller="CafeEntities" asp-action="Index">Cafes</a>
                        </li> *@
                        @* <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="AppRoles" asp-action="Index">Roles</a>
<<<<<<< Updated upstream
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="CartItems" asp-action="Index">Cart Items</a>
                        </li>
=======
                        </li> *@
>>>>>>> Stashed changes
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <Partial name="Footer" />

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RolesAuth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OneDrive/Desktop/Unique/Cafe_Project_MS.NET-master/Cafe_System/RolesAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CafeTO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  
    <link rel="stylesheet" href="~/RolesAuth.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary  border-bottom box-shadow mb-3" data-bs-theme="dark">
            @* <nav class="navbar navbar-expand-lg bg-primary box-shadow mb-3" data-bs-theme="dark"> *@
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src='https://cdn-icons-png.flaticon.com/512/9620/9620771.png' alt="Logo" class="navbar-logo" />
                    CafeTo
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" id="AboutUs" asp-controller="Home" asp-action="AboutUs">AboutUs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" id="ContactUs" asp-controller="Home" asp-action="ContactUs">ContactUs</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CafeEntities" asp-action="Index">Cafes</a>
                        </li> *@
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppRoles" asp-action="Index">Roles</a>
                        </li> *@
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <partial name="Footer" />
    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RolesAuth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>